# Use an official Python runtime as a parent image
FROM python:3.8.7

# Set the envs
ENV PROJECT_ROOT /srv/video-call-test/client

# Set the working directory
WORKDIR $PROJECT_ROOT

# Install Jinja2
RUN pip install --upgrade pip
RUN pip install Jinja2
